#!/bin/bin/env bash

# Update apt package index
sudo apt update

# Install Nginx
sudo apt install nginx -y

# Configure Nginx to listen on port 80
sudo sed -i 's/listen\ 80\ default_server;/listen\ 80;/g' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart

# Create index.html file with "Hello World!" message
echo "Hello World!" | sudo tee /var/www/html/index.html

